#!/usr/bin/env python3
"""
build_campaigns.py  —  run this once from your `public/` directory to
generate campaigns.json from all session_*.json files in data/.

Usage:
    cd path/to/sdcs-replay/public
    python ../build_campaigns.py

Or pass paths explicitly:
    python build_campaigns.py --data data/ --output campaigns.json
"""
import json, os, re, sys, argparse

def clean_players(raw_players: dict) -> list:
    """Deduplicate pilot names: strip trailing (N), - NPC, - interpolated, etc."""
    seen, out = set(), []
    for p in raw_players:
        base = re.sub(r'\s*(-\s*(NPC|interpolated|\d+)|[\(\s]\d+\)?)\s*$', '', p, flags=re.I).strip()
        if base and base not in seen:
            seen.add(base)
            out.append(base)
    out.sort(key=str.lower)
    return out

def session_label(filename: str) -> str:
    # Viewer derives its own label from sess.date — this is just a fallback
    m = re.search(r'session_(\d{4})(\d{2})(\d{2})_(\d{2})(\d{2})(\d{2})', filename)
    if m:
        yr,mo,dy,hh,mm,_ = m.groups()
        return f"{yr}/{mo}/{dy} {hh}:{mm}"
    return filename

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--data',   default='data',          help='Path to session JSON directory')
    parser.add_argument('--output', default='campaigns.json', help='Output path')
    parser.add_argument('--name',   default='Germany Campaign', help='Campaign display name')
    parser.add_argument('--id',     default='germany_campaign', help='Campaign ID slug')
    parser.add_argument('--map',    default='Germany',        help='Map name')
    parser.add_argument('--cid',    default=192, type=int,    help='Campaign geodata ID (192=Germany)')
    args = parser.parse_args()

    data_dir = args.data
    if not os.path.isdir(data_dir):
        print(f"ERROR: data directory not found: {data_dir}", file=sys.stderr)
        sys.exit(1)

    session_files = sorted(
        f for f in os.listdir(data_dir)
        if f.startswith('session_') and f.endswith('.json')
    )

    if not session_files:
        print(f"No session_*.json files found in {data_dir}", file=sys.stderr)
        sys.exit(1)

    sessions = []
    for fname in session_files:
        path = os.path.join(data_dir, fname)
        try:
            with open(path, encoding='utf-8') as f:
                d = json.load(f)
            meta = d.get('meta', {})
            players = clean_players(list(d.get('players', {}).keys()))
            m = re.search(r'session_(\d{4})(\d{2})(\d{2})_(\d{2})(\d{2})(\d{2})', fname)
            date_str = f"{m.group(1)}-{m.group(2)}-{m.group(3)}T{m.group(4)}:{m.group(5)}:{m.group(6)}Z" if m else None
            sessions.append({
                "file":           fname,
                "label":          session_label(fname),
                "date":           date_str,
                "duration_hours": round(meta.get('duration_hours', 0), 2),
                "players":        players,
                "kill_count":     meta.get('kill_count', 0),
            })
            print(f"  ✓ {fname}  ({meta.get('duration_hours',0):.2f}h, {meta.get('kill_count',0)} kills, {len(players)} players)")
        except Exception as e:
            print(f"  ✗ {fname}: {e}", file=sys.stderr)

    # Check for existing campaigns.json and preserve other campaigns
    output_path = args.output
    existing = {"campaigns": []}
    if os.path.exists(output_path):
        try:
            with open(output_path, encoding='utf-8') as f:
                existing = json.load(f)
        except:
            pass

    # Find or create our campaign entry
    camps = existing.get("campaigns", [])
    entry = next((c for c in camps if c.get("id") == args.id), None)
    if entry is None:
        entry = {"id": args.id, "name": args.name, "map": args.map, "campaign_id": args.cid}
        camps.append(entry)
    entry["sessions"] = sessions

    out = {
        "_comment": "SDCS Campaign Registry — generated by build_campaigns.py",
        "campaigns": camps,
    }
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(out, f, indent=2, ensure_ascii=False)

    print(f"\n✓ Written {len(sessions)} sessions to {output_path}")

if __name__ == '__main__':
    main()
